<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />




<title>Reshaping data frames with dplyr</title>

<script src="libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="libs/bootstrap-3.3.5/shim/respond.min.js"></script>


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>


<div class="container-fluid main-container">

<!-- tabsets -->
<script src="libs/navigation-1.1/tabsets.js"></script>
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Reshaping data frames with dplyr</h1>

</div>


<hr />
<ul>
<li><a href="#motivation">What, and why?</a><br />
</li>
<li><a href="#tidydata">Data formats and tidy data</a></li>
<li><a href="#proselytize">Converting between long and wide formats</a>
<ul>
<li><a href="#separate">One more trick: <code>separate</code></a>
<ul>
<li><em><a href="#challengeDataFormat">Challenge</a></em></li>
</ul></li>
</ul></li>
<li><a href="#resources">Resources</a></li>
</ul>
<hr />
<div id="motivation" class="section level1">
<h1>Why, and what?</h1>
<p>Sometimes you may have several different data frames with data on the same set of samples, and you’d like to put them together into one data frame. If these separate data frames are set up differently from each other, you may need to restructure one or both to more easily align them. Or, your data may be in one data frame, but not in a form that works with the analysis functions that you want to use (e.g., for statistics).</p>
<p>In the next two lessons, we will introduce you to reshaping functions from the package <code>tidyr</code> and join functions from the package <code>dplyr</code>, which you’ve already had some experience with. These functions will help you organize your data for analysis both in terms of making your data “tidy” as well as putting all observations or variables into the same data frame.</p>
<p>Let’s start by installing the package <code>tidyr</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install.packages</span>(<span class="st">&quot;tidyr&quot;</span>)   ## install the package</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(<span class="st">&quot;tidyr&quot;</span>)   ## load the package</code></pre></div>
</div>
<div id="tidydata" class="section level1">
<h1>Data formats and tidy data</h1>
<p>Data frames can be in either long format or wide format.</p>
<p>To demonstrate, let’s read in a data frame in long format: <code>nutrients_long</code>. There are three different measurements for each sample: ammonium, nitrate, and nitrite. All of the values are in a single column, <code>Concentration</code>, and the measurement is specified by a value in a second column, <code>Nutrient</code>. In <code>tidyr</code> and other similar packages, this variable (<code>Nutrient</code>) is called the <em>key</em>.</p>
<!--
## Originally written out, but it seemed unnecessarily time consuming, so now it's read in.
## This is here to re-create it if I'd like to.
nutrients_long <- data.frame(SampleID = rep(c(1, 2, 3), 3)
                        ,Nutrient = c(rep("Ammonium",3), rep("Nitrate",3), rep("Nitrite",3)) 
                        ,Concentration = c(8.2, 6.9, 12.1, 1.7, 3.6, 2.8, 0.4, 1.5, 0.8)
                        )
write.csv(nutrients_long,"Data/nutrients_long.csv", row.names=FALSE)
-->
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nutrients_long &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;Data/nutrients_long.csv&quot;</span>)
nutrients_long</code></pre></div>
<pre><code>##   SampleID Nutrient Concentration
## 1        1 Ammonium           8.2
## 2        2 Ammonium           6.9
## 3        3 Ammonium          12.1
## 4        1  Nitrate           1.7
## 5        2  Nitrate           3.6
## 6        3  Nitrate           2.8
## 7        1  Nitrite           0.4
## 8        2  Nitrite           1.5
## 9        3  Nitrite           0.8</code></pre>
<p>Here is the same data frame, using color to help you visualize the structure:</p>
<p><img src="Images/DataBlocks_long.png" width="360pt" style="display: block; margin: auto;" /></p>
<p>But what if we want all of the data from one sample to be in a single row, with each nutrient in a separate column? This would be called wide format, and it would look like this:</p>
<p><img src="Images/DataBlocks_wide.png" width="480pt" style="display: block; margin: auto;" /></p>
<p>This is an example of “tidy” data (<a href="https://www.jstatsoft.org/article/view/v059i10">Wickham 2014</a>). It has the following characteristics:</p>
<ol style="list-style-type: decimal">
<li>Each variable forms a column.</li>
<li>Each observation forms a row.</li>
</ol>
<p>Formatting your data in this way can streamline downstream analyses. A consistent data format makes it easier to pass data to functions and analyses.</p>
<p>Of course, there are other structures and formats that may be more convenient for other purposes, but this one tends to be the most effective for analysis in R.</p>
<p>The data you work with is likely more complex than in this example, and it can take some thought to decide what constitutes a variable.</p>
<p>If the structure of your experiment involves groups between which you want to compare aggregate data (mean, maximum, etc.), these groups should usually be specified by a variable (i.e., a column), with each sample in each group in a separate row. For example, say you have two treatments applied to each <code>SampleID</code>, and you want to compare nutrient concentrations between treatments. Ideally, you would include a <code>Treatment</code> variable in your data frame, and each <code>SampleID</code> would be associated with 2 rows, one for each <code>Treatment</code>. The structure would be the same if you had multiple sampling dates instead of multiple treatments. It would also be similar if you had two <code>Treatments</code> that each had 3 replicates, with the variable name <code>Replicate</code> replacing <code>SampleID</code>.</p>
<p><img src="Images/DataBlocks_wide_reps.png" width="600pt" style="display: block; margin: auto;" /></p>
<p>This is a tidy dataset!</p>
<p>In contrast, the following “messy” dataset has separate columns for different replicates of each treatment. This will make things much more difficult later and should be avoided. However, if your data comes this way, e.g. as output from an analytical instrument, it is straightforward to use reshaping functions to put it into a tidier form!</p>
<p><img src="Images/DataBlocks_wide_awful.png" width="900pt" style="display: block; margin: auto;" /></p>
<p>For more on tidy data, here is Hadley Wickham’s informal version of his full tidy data paper: <a href="https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html" class="uri">https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html</a></p>
</div>
<div id="proselytize" class="section level1">
<h1>Converting between long and wide formats</h1>
<p>Depending on the initial format of the data that you are working with, it may be necessary to convert it between long and wide format (and possibly in both directions) to make it tidy.</p>
<p>A simple way to convert your data from long to wide format is to use the function <code>spread</code> in <code>tidyr</code>. Here, we’ll start with the data frame <code>nutrients_long</code> and convert it to wide format. As a reminder, here is the <code>nutrients_long</code> data frame:</p>
<pre><code>##   SampleID Nutrient Concentration
## 1        1 Ammonium           8.2
## 2        2 Ammonium           6.9
## 3        3 Ammonium          12.1
## 4        1  Nitrate           1.7
## 5        2  Nitrate           3.6
## 6        3  Nitrate           2.8
## 7        1  Nitrite           0.4
## 8        2  Nitrite           1.5
## 9        3  Nitrite           0.8</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nutrients_wide &lt;-<span class="st"> </span>nutrients_long %&gt;%<span class="st"> </span>
<span class="st">  </span><span class="kw">spread</span>(<span class="dt">key =</span> Nutrient, <span class="dt">value =</span> Concentration)

nutrients_wide</code></pre></div>
<pre><code>##   SampleID Ammonium Nitrate Nitrite
## 1        1      8.2     1.7     0.4
## 2        2      6.9     3.6     1.5
## 3        3     12.1     2.8     0.8</code></pre>
<p>In the function <code>spread</code>, the <code>key</code> argument is the name of the column that contains a list of the data descriptors (or measurement names) that we want to separate, and these descriptors will become column names in wide format. The <code>value</code> argument indicates the values that will populate the data frame.</p>
<p>Tip: When you’re figuring out how to restructure your data for a downstream analysis, it can be helpful to write out a quick sketch of how you want the data to be organized, in terms of the names of the variables and the observations. This may help you figure out what input to give to each argument in the reshaping function.</p>
<p>We can convert wide format data back to long format using the function <code>gather</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nutrients_wide %&gt;%
<span class="st">  </span><span class="kw">gather</span>(<span class="dt">key =</span> <span class="st">&quot;Nutrient&quot;</span>, <span class="dt">value =</span> <span class="st">&quot;Concentration&quot;</span>, Ammonium, Nitrate, Nitrite)</code></pre></div>
<pre><code>##   SampleID Nutrient Concentration
## 1        1 Ammonium           8.2
## 2        2 Ammonium           6.9
## 3        3 Ammonium          12.1
## 4        1  Nitrate           1.7
## 5        2  Nitrate           3.6
## 6        3  Nitrate           2.8
## 7        1  Nitrite           0.4
## 8        2  Nitrite           1.5
## 9        3  Nitrite           0.8</code></pre>
<p>In this case, the argument <code>key</code> gives the <em>name</em> of the column that will have the data descriptors in it (here, “Nutrient”), and the argument <code>value</code> has the <em>name</em> of the column with the values (here, “Concentration”). The remaining input tells the function which variables to gather. In this case, this is a list of columns. For each column, the column name will be used to populate the named key column, and the values will be used to populate the named value column. SampleID is not listed and is maintained as an identifier for each observation - i.e., it is not gathered.</p>
<p>You can accomplish the same task by telling R that you want to gather all of the columns besides SampleID, as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nutrients_wide %&gt;%
<span class="st">  </span><span class="kw">gather</span>(<span class="dt">key =</span> <span class="st">&quot;Nutrient&quot;</span>, <span class="dt">value =</span> <span class="st">&quot;Concentration&quot;</span>, -SampleID)</code></pre></div>
<p>You can also specify these columns using column numbers. Try these yourself to demonstrate that they give the same output.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nutrients_wide %&gt;%
<span class="st">  </span><span class="kw">gather</span>(<span class="dt">key =</span> <span class="st">&quot;Nutrient&quot;</span>, <span class="dt">value =</span> <span class="st">&quot;Concentration&quot;</span>, <span class="dv">2</span>:<span class="dv">4</span>)

nutrients_wide %&gt;%
<span class="st">  </span><span class="kw">gather</span>(<span class="dt">key =</span> <span class="st">&quot;Nutrient&quot;</span>, <span class="dt">value =</span> <span class="st">&quot;Concentration&quot;</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>)</code></pre></div>
<p>What happens if you only select two of the three columns of data?</p>
<div id="one-more-trick-separate" class="section level2">
<h2>One more trick: <code id="separate">separate</code></h2>
<p>Sometimes a variable may contain information that really makes up two variables. For example, the following data frame has one column that indicates both the nutrient analyzed and the sample replicate.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nutrients_dbl &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;Data/nutrients_dbl.csv&quot;</span>)
nutrients_dbl</code></pre></div>
<pre><code>##    Treatment Nutrient_Rep Concentration
## 1          1   Ammonium_1           8.2
## 2          2   Ammonium_1          10.5
## 3          1    Nitrate_1           1.7
## 4          2    Nitrate_1           0.4
## 5          1    Nitrite_1           0.4
## 6          2    Nitrite_1           0.7
## 7          1   Ammonium_2           6.9
## 8          2   Ammonium_2           8.6
## 9          1    Nitrate_2           3.6
## 10         2    Nitrate_2           2.7
## 11         1    Nitrite_2           1.5
## 12         2    Nitrite_2           1.2
## 13         1   Ammonium_3          12.1
## 14         2   Ammonium_3           7.8
## 15         1    Nitrate_3           2.8
## 16         2    Nitrate_3           4.1
## 17         1    Nitrite_3           0.8
## 18         2    Nitrite_3           0.9</code></pre>
<p>We can separate that one variable into two new variables using the function <code>separate</code>. We will use <code>col</code> to specify which column to separate, <code>sep</code> to specify what character to separate on (i.e., the one that currently joins the two variables), and <code>into</code> to specify the names of the new columns.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nutrients_dbl %&gt;%<span class="st"> </span><span class="kw">separate</span>(<span class="dt">col=</span>Nutrient_Rep, <span class="dt">sep=</span><span class="st">&quot;_&quot;</span>, <span class="dt">into=</span><span class="kw">c</span>(<span class="st">&quot;Nutrient&quot;</span>, <span class="st">&quot;Rep&quot;</span>)) </code></pre></div>
<pre><code>##    Treatment Nutrient Rep Concentration
## 1          1 Ammonium   1           8.2
## 2          2 Ammonium   1          10.5
## 3          1  Nitrate   1           1.7
## 4          2  Nitrate   1           0.4
## 5          1  Nitrite   1           0.4
## 6          2  Nitrite   1           0.7
## 7          1 Ammonium   2           6.9
## 8          2 Ammonium   2           8.6
## 9          1  Nitrate   2           3.6
## 10         2  Nitrate   2           2.7
## 11         1  Nitrite   2           1.5
## 12         2  Nitrite   2           1.2
## 13         1 Ammonium   3          12.1
## 14         2 Ammonium   3           7.8
## 15         1  Nitrate   3           2.8
## 16         2  Nitrate   3           4.1
## 17         1  Nitrite   3           0.8
## 18         2  Nitrite   3           0.9</code></pre>
<p>Voilà! One column has become two. Now we are in a position to further tidy the data frame, as we will see below.</p>
<div id="challengeDataFormat" class="section level4">
<h4>Challenge</h4>
<ol style="list-style-type: decimal">
<li><p>The <code>trees</code> data frame is in long format: every observation (count) is in its own row, and the tree species is specified by the variable <code>Species</code>. Convert this data frame to wide format, with counts for different species in different columns.</p></li>
<li><p>Similarly, convert the original <code>trees</code> data frame to wide format, but with data from different plot replicates (specified by <code>Plot</code>) in different columns.</p></li>
<li><p>Sometimes it may take multiple steps to tidy a dataset! Above, we used <code>separate</code> to start to put <code>nutrients_dbl</code> into a tidier form. Do this again, but now convert the new, <code>separate</code>d data frame into a tidy data frame in wide format, with concentrations of different nutrients in different columns.</p></li>
<li><p>Let’s start one step back! Use <code>gather</code>, <code>spread</code>, and <code>separate</code> to tidy a “messy” data set (“Experiment_nutrients_messy.csv”) into a tidy one, i.e., by converting it to <code>nutrients_dbl</code> and then tidying it as above.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">nutrients_messy &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="dt">file=</span><span class="st">&quot;Data/Experiment_nutrients_messy.csv&quot;</span>)
nutrients_messy</code></pre></div>
<pre><code>##   Treatment Ammonium_1 Nitrate_1 Nitrite_1 Ammonium_2 Nitrate_2 Nitrite_2
## 1         1        8.2       1.7       0.4        6.9       3.6       1.5
## 2         2       10.5       0.4       0.7        8.6       2.7       1.2
##   Ammonium_3 Nitrate_3 Nitrite_3
## 1       12.1       2.8       0.8
## 2        7.8       4.1       0.9</code></pre></li>
</ol>
<hr />
</div>
</div>
</div>
<div id="resources" class="section level1">
<h1>Resources</h1>
<ul>
<li><a href="https://cran.r-project.org/web/packages/tidyr/vignettes/tidy-data.html">Hadley Wickham on tidy data</a></li>
</ul>
<br>
<hr>
<p><br></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
$(document).ready(function () {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
});

</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
