---
title: "Introduction to R for Ecological Data Analysis"
author: "CRI CREATE Workshop"
output:
  html_document:
    keep_md: yes
  pdf_document: default
layout: topic
---
___

Welcome to Introduction to R for Ecological Data Analysis, a 2-day workshop at the University of New Brunswick taught by [Dr. Lindsay Brin](http://www.lindsaydbrin.com). This workshop is part of the [Watershed and Aquatics Training in Environmental Research (WATER)](http://canadianriversinstitute.com/training/water-program/) program at the [Canadian Rivers Institute](http://canadianriversinstitute.com), funded by an NSERC Collaborative Research and Training Experience (CREATE) grant. 

The in-person workshop covers most of the lessons below, roughly in the order in which they are listed. Additional content is provided on this site as a reference. (For example: in the control structures lesson, we will cover if statements in class, but lesson materials for for loops are also provided here; the same is true for simple versus multiple regression, the latter of which we will refer to only briefly.)

The workshop builds off the [Data Carpentry](http://www.datacarpentry.org) lessons on [R for data analysis for Ecology](http://www.datacarpentry.org/R-ecology-lesson/), which are distributed under the [CC-BY license](https://creativecommons.org/licenses/by/2.0/).  The alternate versions of these lessons follow the Data Carpentry lesson plan very closely but are re-written to include CRI workshop-specific data sets and to provide more details to allow participants to more easily go through lessons on their own (i.e., when missing a portion of the workshop for required classes).

Course details can be found [below](#courseInfo). Data for the workshop can be downloaded from [github](https://github.com/lindsaydbrin/CREATE_R_Workshop/blob/master/DataForParticipants.zip). This information can be accessed online at [http://lindsaydbrin.github.io/CREATE_R_Workshop](http://lindsaydbrin.github.io/CREATE_R_Workshop/).

___

## Workshop lessons outline

#### Introduction to R
* Organization and R Basics
	- [Organization and R basics *(CRI version)*](Lesson_-_Organization_and_R_Basics.html)
	- [Before we start *(Data Carpentry)*](http://www.datacarpentry.org/R-ecology-lesson/00-before-we-start.html)
* Introduction to R
	- [*CRI version*](Lesson_-_Introduction_to_R.html)
	- [*Data Carpentry*](http://www.datacarpentry.org/R-ecology-lesson/01-intro-to-R.html)

#### Working with Data
* Starting with data 
	- [*CRI version*](Lesson_-_Starting_with_data.html)
	- [*Data Carpentry*](http://www.datacarpentry.org/R-ecology-lesson/02-starting-with-data.html)
* The `data.frame` class
	- *CRI version*
		- [The `data.frame` class - part 1](Lesson_-_Data_Frame_Part_1.html)
		- [The `data.frame` class - part 2 (Substitute for second half of Data Carpentry lesson)](Lesson_-_Data_Frame_Part_2.html)
	- [*Data Carpentry*](http://www.datacarpentry.org/R-ecology-lesson/03-data-frames.html)

#### Data manipulation
* Data manipulation using `dplyr` 
	- [*CRI version*](Lesson_-_dplyr_data_handling.html)
	- [*Data Carpentry*](http://www.datacarpentry.org/R-ecology-lesson/04-dplyr.html)
* [Reshaping data frames: `dplyr` reshape](Lesson_-_dplyr_reshape.html)
* [Joining data frames: `dplyr` join](Lesson_-_dplyr_join.html)

#### Pull it all together
* [Day 1 Scripting Challenge](Lesson_-_Day_1_Scripting_Challenge.html)

#### Computing
* Control structures
	- [if statements](Lesson_-_ControlStr_if.html)
	- [for loops](Lesson_-_ControlStr_for.html)
* [Writing functions](Lesson_-_Writing_functions.html)

#### Data visualization
* [Plotting with the base package](Lesson_-_Plotting_Base_Package.html)
* [Plotting with ggplot2 *(Data Carpentry)*](http://www.datacarpentry.org/R-ecology-lesson/05-visualization-ggplot2.html)

#### Statistical tests in R
* [Linear regression: Simple and multiple](Lesson_-_Linear_regression.html)
* [Analysis of variance: One-way and two-way](Lesson_-_ANOVA.html)

#### Pull it all together
* [Data Workflow Challenge](Lesson_-_Data_Workflow_Challenge.html)

<br>

___

##Course details {#courseInfo}

**Course overview**

R is a powerful, free, open-source, and widely used tool for working with data that can allow you to streamline your analysis process, increase reproducibility, catch and avoid mistakes, and access newly developed analyses and statistical approaches. 

This workshop will provide participants with the tools for reading in, manipulating, analyzing, and visualizing data in R.  For example, we will cover topics such as cleaning and organizing data, joining data sets, working with factors, writing functions, using for loops and if…else statements, etc.   

A primary goal is to help participants become comfortable working in a coding environment. To accomplish this, the workshop format will include a combination of explanation, demonstration, and extensive hands-on practice using a variety of sample datasets.  Participants will leave with basic skills that can be put into use immediately, as well as a platform from which to learn more complex analyses.

**Learning objectives**

At the end of this 2-day workshop, participants will:

* Have a conceptual understanding of how R works
* Be aware of the availability of relevant packages to expand R’s functionality
* Be able to use R as a calculator and basic data manipulation tool
* Be able to write simple functions in R to automate analyses
* Be able to produce useful graphical and numeric summaries of data
* Be able to implement basic statistical tests (ANOVA, linear regression)


<br>
<hr>
<br>