---
title: "R lessons for CRI R Workshop"
author: "2016 June 23-24"
output:
  pdf_document: default
  html_document:
    keep_md: yes
layout: topic
---
___

#### Introduction to R
* [Before we start *(Data Carpentry)*](http://www.datacarpentry.org/R-ecology-lesson/00-before-we-start.html)
* [Introduction to R *(Data Carpentry)*](http://www.datacarpentry.org/R-ecology-lesson/01-intro-to-R.html)

#### Working with Data
* [Starting with data *(Data Carpentry)*](http://www.datacarpentry.org/R-ecology-lesson/02-starting-with-data.html)
* [The `data.frame` class *(Data Carpentry)*](http://www.datacarpentry.org/R-ecology-lesson/03-data-frames.html)

#### Data manipulation
* [Data manipulation using `dplyr` *(Data Carpentry)*](http://www.datacarpentry.org/R-ecology-lesson/04-dplyr.html)
* [Reshaping data frames: `dplyr` reshape](Lesson_-_dplyr_reshape.pdf)
* [Joining data frames: `dplyr` join](Lesson_-_dplyr_join.pdf)

#### Data visualization
* [Plotting with the base package](Lesson_-_Plotting_Base_Package.pdf)
* [Plotting with ggplot2 *(Data Carpentry)*](http://www.datacarpentry.org/R-ecology-lesson/05-visualization-ggplot2.html)

#### Computing
* [Control structures](Lesson_-_Control_structures.pdf)
* [Writing functions](Lesson_-_Writing_functions.pdf)

#### Statistical tests in R
* [Linear regression: Simple and multiple](Lesson_-_Linear_regression.pdf)
* [Analysis of variance: One-way and two-way](Lesson_-_ANOVA.pdf)

#### Pull it all together
* [Data Workflow Challenge](Lesson_-_Data_Workflow_Challenge.pdf)
* [Data Workflow Challenge: One possible solution](Lesson_-_Data_Workflow_Challenge_Solutions.pdf)

<br>
<hr>
<br>